language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '12'
  - '11'
  - '10'

after_success:
  - npm run coverage
  - npm run build

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        script:
          - npx semantic-release
